<?php
use Drupal\webform\WebformInterface;

/**
 * @file
 * searches for Cookies and adds to them to a webform'
 */

/**
 * Implements hook_theme().
 */
function webform_cookies_handler_theme() {
  return [
    'webform_handler_cookies_summary' => [
      'variables' => ['settings' => NULL, 'handler' => []],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function webform_cookies_handler_webform_insert(WebformInterface $webform) {
  /** @var \Drupal\webform\Plugin\WebformHandlerManagerInterface $handler_manager */
  $handler_manager = \Drupal::service('plugin.manager.webform.handler');

  // Create webform handler.
  $handler_configuration = [
    'id' => 'webform_cookies_handler',
    'label' => 'Webform Cookies',
    'handler_id' => 'webform_cookies_handler',
    'status' => 1,
    'weight' => 0,
    'settings' => [],
  ];
  $handler = $handler_manager->createInstance('webform_cookies_handler', $handler_configuration);

  // Must set original id so that the webform can be resaved.
  $webform->setOriginalId($webform->id());

  // Add webform handler which triggers Webform::save().
  $webform->addWebformHandler($handler);
}
