
<?php
use Drupal\webform_cookies_handler\Plugin\WebformHandler\CookiesWebformHandler;
use Drupal\webform\WebformInterface;

/**
 * @file
 * searches for Cookies and adds to them to a webform'
 */

/**
 * Implements hook_theme().
 */
function webform_cookies_handler_theme() {
  return [
    'webform_handler_cookies_summary' => [
      'variables' => ['settings' => NULL, 'handler' => []],
    ],
  ];
}



/**
 * Implements hook_ENTITY_TYPE_insert().
 */

function webform_cookies_handler_webform_insert(WebformInterface $webform) {
  /** @var \Drupal\webform\Plugin\WebformHandlerManagerInterface $handler_manager */
  // Create webform handler.
  // TODO: Pull from module configuration settings
  $default_cookies = '_gid, _gad';
  $handler_manager = \Drupal::service('plugin.manager.webform.handler');
  
  $handler_configuration = [
    'id' => 'webform_cookies',
    'label' => 'webform_cookies',
    'handler_id' => 'webform_cookies',
    'status' => 1,
    'weight' => 0,
    'settings' => array(
      'cookies' => $default_cookies,
      'string_matching' => FALSE,
      'tokens' => [],
    ),
    
  ];
  
  $handler = $handler_manager->createInstance('Webform Cookies', $handler_configuration);
  

  // Must set original id so that the webform can be resaved.
  $webform->setOriginalId($webform->id());

  // Add webform handler which triggers Webform::save().
  $webform->addWebformHandler($handler);

}

